### ISSUE TITLE
Unable to use our jenkins credential

### ISSUE THREAD

**Issue by panmanphil** [Microsoft/azure-app-service-plugin#24]
I am trying to deploy a web app using this plugin for the first time, using Jenkins credentials from a service principal we have been using for awhile now. We have not use them for this purpose and I have a feeling that may be where our problem lies, but don't know what permission to grant to make it work specifically in portal.azure.com. 

Using just the pipeline syntax helper in jenkins, selecting the credential id we have setup we get this exception:

```
com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS50001: The application named https:\/\/portal.azure.com\/ was not found in the tenant named xxxxxx-xxxxxxx  This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant.  You might have sent your authentication request to the wrong tenant.
```

The service principal currently has azure active directory and Azure Service Management API in required permissions. Is there another we need to grant? 

We get the same error in a pipeline step like this
```
node {
        azureWebAppPublish azureCredentialsId: 'xxxx-xxx-xxx--xxxxx', publishType: 'file',
                   resourceGroup: 'xxxxx-preprod-rp', appName: 'xxxxxxx-dev-app',
                   sourceDirectory: '.build/websites', targetDirectory: 'wwwroot/xxxxxx-dev-app'
    }
```
Any guidance would be appreciated, thanks

**Comment by ArchangelSDY** [comment]
Not very familiar with AAD. I guess at least [Website Contributor Role](https://docs.microsoft.com/en-us/azure/active-directory/role-based-access-built-in-roles#website-contributor) is required to deploy an web app. You'd better also check that the client id/client secret/endpoints in your Azure Credentials are correct.

**Comment by panmanphil** [comment]
It turned out I could see there was a problem with the Azure Credentials, reproducible with the Verify button in the credential setup. I corrected that, and all is well, thanks for the help
