### ISSUE TITLE
git add produce  "is outside repository" error.

### ISSUE THREAD

**Issue by dmitrykudriavtsev** [Microsoft/azure-app-service-plugin#26]
Hello!
i have error during running Jenkins pipelie:
how i can resolve this?
tnx

```
        azureWebAppPublish azureCredentialsId: 'azurecred',
                publishType: 'file',
                filePath: '',
                resourceGroup: '***',
                appName: '***',
                sourceDirectory: 'Main/Source/out',
                targetDirectory: ''
```

**part of logs:**

Starting Azure Web App Deployment
Cloning repository https://***.scm.azurewebsites.net:443/*.git
 > git init C:\jenkins\workspace\masterad1fd555\.azure-deploy # timeout=10
Fetching upstream changes from https://tcdev-ne.scm.azurewebsites.net:443/*.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --tags --progress https://***.scm.azurewebsites.net:443/*.git +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url https://***.scm.azurewebsites.net:443/*.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
Seen branch in repository origin/master
Seen 1 remote branch
 > git config core.sparsecheckout # timeout=10
 > git checkout -f master
 > git add C:/jenkins/workspace/masterad1fd555/Main/Source/out/Content/bootstrap-theme.css # timeout=10
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

hudson.plugins.git.GitException: Command "git add C:/jenkins/workspace/masterad1fd555/Main/Source/out/Content/bootstrap-theme.css" returned status code 128:
stdout: 
stderr: fatal: C:/jenkins/workspace/masterad1fd555/Main/Source/out/Content/bootstrap-theme.css: 'C:/jenkins/workspace/masterad1fd555/Main/Source/out/Content/bootstrap-theme.css' **is outside repository**

**Comment by ArchangelSDY** [comment]
How did you set the `filePath` ? It should not be left blank.

**Comment by dmitrykudriavtsev** [comment]
how i see in code and samples, filePath is only pattern of files for deploy, so blank is mean all files and dirs.

**Comment by ArchangelSDY** [comment]
Looks like your jenkins instance has some issues to manipulate file path. What's your jenkins version? Do you use any other plugin in your job?

Besides, I've created a [debug version](https://www.dropbox.com/s/i1k4p3aerf3s9rl/azure-app-service.hpi?dl=0) with more verbose logs. Could you install it and paste build output here?

**Comment by dmitrykudriavtsev** [comment]
i found mistake. 
its about path in slave workdir configuration:
was c:/jenkins
should c:\\jenkins
thats result:
not working: git add C:/jenkins/workspace/masterad1fd555/Main/Source/out/Content/bootstrap-theme.css
working: git add Content/bootstrap-theme.css # timeout=10
