### ISSUE TITLE
Should create a new resource group when there is no such one existing.

### ISSUE THREAD

**Issue by HuanhuanSunMSFT** [Microsoft/azure-app-service-plugin#3]
Log:

Started by user anonymous
Building in workspace D:\Github\azure-webapp-plugin\work\jobs\webapp7\workspace
Starting Azure Container Service Deployment
Creating resource group 'webappdebuggroup1' if it does not exist
Checking if the Azure Webapp with name 'webappdebuggroup1' exist.
ERROR: Error creating resource group:timeout
Build step 'Azure Webapp Configuration' marked build as failure
Finished: FAILURE

**Comment by chenkennt** [comment]
We don't have create functionality anymore, so close it.
